listenOn: localhost:8080
microservices:
  microservice: 
    tenant: dolittle.io/tenant-id
    application: dolittle.io/application-id
    environment: environment
    microservice: dolittle.io/microservice-id
  proxy:
    tenant-header: Tenant-Id
    paths:
      shell:
        container: shell
        port: shell-ws
      runtime/management:
        container: runtime
        port: management