logger:
  format: console
  level: info

proxy:
  port: 8080
  tenant-header: Tenant-ID

  paths:
    shell:
      - container: shell
        port: ws
    runtime-management:
      - container: runtime
        port: management
      - container: runtime
        port: http

kubernetes:
  fields:
    tenant:
      annotations: [ dolittle.io/tenant-id ]
    application:
      annotations: [ dolittle.io/application-id ]
    environment:
      labels: [ environment ]
    microservice:
      annotations: [ dolittle.io/microservice-id ]
