version: '3.1'
services:
  data-mongo:
    image: dolittle/mongodb:4.2.2
    ports:
      - 27017:27017
    logging:
      driver: none

  data-runtime-backups:
    image: dolittle/runtime:5.4.1
    volumes:
      - ./Backups/resources.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 9700:9700
      - 50052:50052
      - 50053:50053
