apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customers.dolittle.io
spec:
  group: dolittle.io
  names:
    kind: Customer
    listKind: CustomerList
    plural: customers
    singular: customer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Specification of the kubernetes object.
            properties:
              name:
                type: string
              id:
                pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
                type: string
            required:
            - name
            - id
            type: object
        type: object
    served: true
    storage: true
