apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: microservice-simple
  labels:
    crossplane.io/xrd: xmicroservices.dolittle.io
spec:
  compositeTypeRef:
    apiVersion: dolittle.io/v1alpha1
    kind: XMicroservice
  resources:
  - name: deployment
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: provider-kubernetes
        forProvider:
          manifest:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: dolittle-ms-deployment
              labels:
                app: nginx
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - name: runtime
                    ports:
                    - containerPort: 80
    patches:
    - fromFieldPath: spec.runtime.version
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
      transforms:
      - type: string
        string:
          fmt: "dolittle/runtime:%s"
    - fromFieldPath: spec.runtime.version
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
      transforms:
      - type: string
        string:
          fmt: "dolittle/runtime:%s"
  patchSets:
  - name: namespace
    patches:
    - fromFieldPath: spec.metadata.application-id
      transforms:
      - type: string
        string:
          fmt: "application-%s"
  - name: name
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.metadata.environment
          transforms:
          - type: string
            string:
              type: Convert
              convert: ToLower
        - fromFieldPath: spec.metadata.microservice
          transforms:
          - type: string
            string:
              type: Convert
              convert: ToLower
        strategy: string
        string:
          fmt: "%s-%s"
      policy:
        fromFieldPath: Required