apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: microservice-simple
  labels:
    crossplane.io/xrd: xmicroservices.dolittle.io
spec:
  compositeTypeRef:
    apiVersion: dolittle.io/v1alpha1
    kind: XMicroservice
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: spec.metadata.labels
      toFieldPath: metadata.labels
    - fromFieldPath: spec.metadata.annotations
      toFieldPath: metadata.annotations
    - fromFieldPath: spec.metadata
      toFieldPath: spec.forProvider.manifest.metadata
    - fromFieldPath: spec.metadata.annotations[dolittle.io/application-id]
      toFieldPath: spec.forProvider.manifest.metadata.namespace
      transforms:
      - type: string
        string:
          fmt: "application-%s"
  resources:
  - name: deployment
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: provider-kubernetes
        forProvider:
          manifest:
            apiVersion: apps/v1
            kind: Deployment
            spec:
              replicas: 1
              template:
                spec:
                  containers:
                  - name: runtime
                    ports:
                    - containerPort: 80
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.metadata
      toFieldPath: spec.forProvider.manifest.spec.template.metadata
    - fromFieldPath: spec.metadata.labels
      toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels
    - fromFieldPath: spec.deployment.name
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.deployment.runtime.version
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
      transforms:
      - type: string
        string:
          fmt: "dolittle/runtime:%s"