---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  namespace: system-cert-manager
  name: ca-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      system: Cert-Manager
      component: CA-Injector
  template:
    metadata:
      labels:
        system: Cert-Manager
        component: CA-Injector
    spec:
      serviceAccountName: ca-injector
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ca-injector
          image: "quay.io/jetstack/cert-manager-cainjector:v1.10.0"
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --leader-election-namespace=system-cert-manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  namespace: system-cert-manager
  name: ca-injector
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  name: system-cert-manager-ca-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-cert-manager-ca-injector
subjects:
  - kind: ServiceAccount
    namespace: system-cert-manager
    name: ca-injector
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  name: system-cert-manager-ca-injector
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  namespace: system-cert-manager
  name: ca-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ca-injector
subjects:
  - kind: ServiceAccount
    namespace: system-cert-manager
    name: ca-injector
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    system: Cert-Manager
    component: CA-Injector
  namespace: system-cert-manager
  name: ca-injector
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["cert-manager-cainjector-leader-election", "cert-manager-cainjector-leader-election-core"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
