name: Build Router

env:
  SOURCE_PATH: 'Source/Router'

on:
  push:
    branches:
    - '**'
    paths:
    - 'Source/Router/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.19.2"
    - name: Build
      working-directory: ${{ env.SOURCE_PATH }}
      run: go build .
    - name: Test
      working-directory: ${{ env.SOURCE_PATH }}
      run: go test -v ./...
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: ${{ env.SOURCE_PATH }}
        file: ${{ env.SOURCE_PATH }}/Dockerfile
