name: Prod - Backups - Deploy

env:
  SOURCE_PATH: 'Source/Backups'
  DEPLOYMENT_NAME: 'prod-backups'
  DOCKER_IMAGE_TAG: 'dolittle/system-data-backups'
  DOCKER_FILE: 'Source/Backups/Head/Dockerfile'

on:
  pull_request:
    branches:
    - 'main'
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2
      with:
        version-file: '${{ env.SOURCE_PATH }}/microservice.json'

    - name: Increment version
      id: increment-version
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/increment-version-action@v2
      with:
        version: ${{ steps.context.outputs.current-version }}
        release-type: ${{ steps.context.outputs.release-type }}

    - name: Invoke deploy
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: DeployMicroservice
        token: ${{ secrets.BUILD_PAT }}
        ref: ${{ github.event.sha }}
        inputs: '{ "dockerfile":"${{ env.DOCKER_FILE }}", "docker-image-tag":"${{ env.DOCKER_IMAGE_TAG }}", "deployment": "${{ env.DEPLOYMENT_NAME }}", "version": "${{ steps.increment-version.outputs.next-version }}", "source-path": "${{ env.SOURCE_PATH }}" }'
